name: demo 

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: run demo code base using action
    runs-on: ubuntu-latest
    steps: 
      - name: checking out code
        uses: actions/checkout@v3
    
      - name: Run demo
        uses: ./
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
