name: demo 

on: push

jobs:
  demo:
    name: demo code base
    runs-on: ubuntu-latest
    steps: 
      - name: checking out code
        uses: actions/checkout@v2
    
      - name: Run demo
        uses: ./.github/workflows/demo
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
